### ISSUE TITLE
Bot crashes after sending command

### ISSUE THREAD

**Issue by alexppmax** [gderaco/cryptocurrencyircbot#1]
Here is the console log

> /home/alex/cryptocurrencyircbot/node_modules/irc/lib/irc.js:849

> throw err;
> ^

> Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:144:17)
    at Client.<anonymous> (/home/alex/cryptocurrencyircbot/node_modules/irc/lib/irc.js:643:26)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (/home/alex/cryptocurrencyircbot/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (/home/alex/cryptocurrencyircbot/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

**Comment by gderaco** [comment]
Hello Alex,
I cannot reproduce the error; what you mean by _sending command_?

**Comment by alexppmax** [comment]
Configured the bot, connected the bot to the irc server, joined the channel.

When I send a command in the irc client the bot instead of replying to eg. '!siacoin' crashes and quits with the attached error log.

**Comment by gderaco** [comment]
I'm sorry Alex but I really cannot reproduce the error you're experiencing.

**Comment by gderaco** [comment]
@alex-strafalogea I've tested the bot with nodejs v8.1.1 and v8.0.0 and it works. Please try to use one of these versions.

**Comment by alexppmax** [comment]
@gderaco thanks for the updates. my nodejs was probably outdated. I will try upgrading that and report back

**Comment by jacobzlogar** [comment]
@alex-strafalogea try running it with https://www.npmjs.com/package/forever this will help prevent the bot from crashing under some errors and keep it running at a higher fault tolerance
